-- MySQL Script generated by MySQL Workbench
-- 05/20/15 04:19:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema rapucha
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rapucha
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rapucha` DEFAULT CHARACTER SET utf8 ;
USE `rapucha` ;

-- -----------------------------------------------------
-- Table `rapucha`.`stations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rapucha`.`stations` (
  `station_number` SMALLINT(3) UNSIGNED NOT NULL,
  `name` VARCHAR(500) NOT NULL,
  `location` POINT NOT NULL,
  `locks` TINYINT(2) UNSIGNED NOT NULL,
  PRIMARY KEY (`station_number`),
  UNIQUE INDEX `id_station_UNIQUE` (`station_number` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rapucha`.`station_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rapucha`.`station_history` (
  `timestamp` TIMESTAMP NOT NULL,
  `station_number` SMALLINT(3) UNSIGNED NULL DEFAULT NULL,
  `name` VARCHAR(500) NULL DEFAULT NULL,
  `location` POINT NULL DEFAULT NULL,
  `locks` TINYINT(2) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`timestamp`, `station_number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rapucha`.`observations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rapucha`.`observations` (
  `timestamp` TIMESTAMP NOT NULL,
  `observation_epoch` INT UNSIGNED NOT NULL,
  `weather_string` VARCHAR(45) NOT NULL,
  `temp_c` TINYINT UNSIGNED NOT NULL,
  `relative_humidity` TINYINT UNSIGNED NOT NULL,
  `wind_degrees` SMALLINT(3) NOT NULL,
  `wind_kph` TINYINT UNSIGNED NOT NULL,
  `dewpoint_c` TINYINT NOT NULL,
  `heat_index_c` VARCHAR(45) NULL DEFAULT NULL,
  `windchill_c` TINYINT NOT NULL,
  `feelslike_c` TINYINT NOT NULL,
  `visibility_km` TINYINT UNSIGNED NOT NULL,
  `pressure_mb` SMALLINT UNSIGNED NOT NULL,
  `pressure_trend` SMALLINT NOT NULL,
  `icon` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`timestamp`, `observation_epoch`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rapucha`.`bikes_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rapucha`.`bikes_history` (
  `timestamp` TIMESTAMP NOT NULL,
  `station_number` SMALLINT(3) UNSIGNED NOT NULL,
  `bikes` TINYINT(2) UNSIGNED NOT NULL,
  PRIMARY KEY (`timestamp`, `station_number`),
  INDEX `fk_{02D1770C-1BFA-45AD-ACBC-89D74BC58C9E}` (`station_number` ASC),
  CONSTRAINT `fk_{02D1770C-1BFA-45AD-ACBC-89D74BC58C9E}`
    FOREIGN KEY (`station_number`)
    REFERENCES `rapucha`.`stations` (`station_number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rapucha`.`traffic_history_Y`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rapucha`.`traffic_history_Y` (
  `timestamp` TIMESTAMP NOT NULL,
  `station_number` SMALLINT(3) UNSIGNED NOT NULL,
  `no_traffic` BLOB NOT NULL,
  `traffic` BLOB NOT NULL,
  `delta` BLOB NOT NULL,
  PRIMARY KEY (`timestamp`, `station_number`),
  INDEX `fk_{E590C4BA-C449-4943-8229-F6245278FC68}` (`station_number` ASC),
  CONSTRAINT `fk_{E590C4BA-C449-4943-8229-F6245278FC68}`
    FOREIGN KEY (`station_number`)
    REFERENCES `rapucha`.`stations` (`station_number`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
